######################################################################
# Automatically generated by qmake (2.01a) jeu. juin 16 19:55:10 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Mainwindow.h
SOURCES += InfoWindow.cpp \
           JuliaWidget.cpp \
           Main.cpp \
           Mainwindow.cpp \
           MandelWidget.cpp \
           Others.cpp
